#!/bin/bash
set -e
LOGFILE=/home/ec2-user/www/logs/gunicorn/bloop.log
LOGDIR=$(dirname $LOGFILE)
NUM_WORKERS=3
# user/group to run as
USER=ec2-user
GROUP=ec2-user
cd /home/ec2-user/www/bloop
source /home/ec2-user/www/env/bin/activate
test -d $LOGDIR || mkdir -p $LOGDIR
exec gunicorn_django -w $NUM_WORKERS \
--user=$USER \
--group=$GROUP \
--log-level=debug \
--log-file=$LOGFILE 2>>$LOGFILE